language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "EDF1MAY0fuaaYLclOQ/FEggAf+/QKADvb1ybNFNPsliFCM4yHbs5y7CSOO5nx3CPfaDLm7bTFKEI0QMkhYZvSYKcWKBSM2Dms+X4/0jOKtZP8yPvbsY0m0JYuWnRsnN+nvcUxoFgXoNN/p+r4ciz4elVBJGGhRc+efXVfaLsD92EhQBH3e4MChTYUhPbEQqF0XrGsd+cDja3DeqIA50Lifqt8QagAQkgkv/+uFpQhFAHv259/vPJvx9pni12JXRpBIm7NLFNT7Nyj6x4A8V8ItA2tBcXVqd+i9CgGS4cd8kwOctPr148wDNQBNVlfsYW01c0Orfp+CGCCBAeZvsfrx7X1zqai0sAd51B0ijtPiOJ8lJc9gK1G+YKnuKmbn6vzsZgv1IvT8w+GnRqWOFta+0LQQsNXJ1Ka5qDtF+ES+acDV4oxNgGOJJLUPpcQh+zfQP2rhNqh2A8o//DRkyfkYeIX3uRkIA1Fg35Gquh8h0/S7MyprMchdSmxgY8rJHPEw9pRFSjNq17RmX2aWaOoaOf1HKlrjG+XDsIW7jAjBtTl4B0K9rQSeWKdzM0KPbaiZBqjyode2iY24EV+dWsXR7jWireNJnD77VJb6L3NbKQyKJ83yAXyxQkYHJm5jR7IMpwVvoFXl/FbpnUxWFqGqtkVMwhHD9uwDcMGfmQkik="
  api_key: # 4007
    secure: "WYNmcd/T0po7oUmwla3oLjbpg6YKmQjHApNCuxrf9o+P3POYVM9enCz5CsDndvsTfi46Hc+S22y3Davdfs1LVZjwEyn/OF1MDajw6IrMQGKgQyq7RT+yn/d3KzI9tuSrFoXtA579jAmb3V5e8OiLfHWCfpQwsdB5MVnkgOpAzDwMeDEennFb1sXEo9SOEsW/kjGUTRPQNXHnUUxAXONjB9kn57ATg5w55J3BRywwFMzPGdE1H4RqYxAUFOecXtufore0Il1/opvfjmKc4C2Uxf9mLB0/aLEj7j79GUETWsJAY+L9/tlYxj89mNsVcKnIof/nBUpuOnm/yoYHiloGnSOn8xG7A4KmvpQWC9y/SD3i/pCXkRhUi7+TOiapHznoSCFE3eSyGrldNimYvZPq6kUfsuUBQBYlECCosZBOllO2c1MdDc1NMuEp7LssmKJ7QAtVUlrCJ4RUcTazBXt1WMdUPqzVOgRMW2ke0VVnoKeNT4ztHU8Qstzz/5u5jKAp+/MKtyzXBvBsDvSxp6hlMQ8tPG6Jl8tpTY2A7yBhUqEyJHZAglgAM+5o+KwfVbgXU9JfvAbezqDnwbqc503PhF5v4gfFcAiOV+28HqR6Qoqo0T2mDKyZDRA5az2ipj5lCz8AMBZzoZgOgEQfwnPapjovZdXZ2esfqynm4DV8+MA="
  on:
    tags: true
    node: lts/*
